version: '3.8'

services:
  flask_admin:
    container_name: flask_admin
    image: 'aurelienadvanced/flask_admin'
    restart: always
    networks: 
      - web_network

  flask_light:
    container_name: flask_light
    image: 'aurelienadvanced/flask_light'
    restart: always
    networks: 
      - web_network

  flask_material:
    image: 'aurelienadvanced/flask_material'
    restart: always
    networks: 
      - web_network
    deploy:
      mode: replicated
      replicas: 5
  
  flask_soft:
    container_name: flask_soft
    image: 'aurelienadvanced/flask_soft'
    restart: always
    networks: 
      - web_network

  flask_volt:
    container_name: flask_volt
    image: 'aurelienadvanced/flask_soft'
    restart: always
    networks:
      - web_network
    ports:
      - "4004:4004"

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:mainline-alpine-slim"
    ports:
      - "4000:3000"
      - "4001:3001"
      - "4002:3002"
      - "4003:3003"

    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - flask_admin
      - flask_light
      - flask_material
      - flask_soft

networks: 
  web_network:
    driver: bridge