apiVersion: v1
kind: Service
metadata:
  name: flask-material-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 4001
      targetPort: 4001
      nodePort: 3002
      name: flask-np
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-material-deployment
spec:
  selector:
    matchLabels:
      app: flask
    template:
      metadata:
        labels:
          app: flask
      spec:
        containers:
          - name: flask-material
            image: "aurelienadvanced/flask_material"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-material-as
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-material-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15