apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-light-as
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-light-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15