apiVersion: v1
kind: Service
metadata:
  name: flask-light-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30002
    name: flask-np